<%
'Constants

Const GOODIE_CONTENTGROUP_SOUND = "SOUND"
Const GOODIE_CONTENTGROUP_SFX = "SFX"
Const GOODIE_CONTENTGROUP_IMG = "IMG"
Const GOODIE_CONTENTGROUP_ANIM = "ANIM"
Const GOODIE_CONTENTGROUP_VIDEO = "VIDEO"
Const GOODIE_CONTENTGROUP_DOJA = "J2ME"
Const GOODIE_CONTENTGROUP_FRAME = "FRAME"
Const GOODIE_CONTENTGROUP_VIDEO_RGT = "VIDEO_RGT"

Const GOODIE_CONTENTTYPE_LOGO_BW = "LOGO_BW"
Const GOODIE_CONTENTTYPE_IMG_COLOR = "IMG_COLOR"
Const GOODIE_CONTENTTYPE_IMG_BW = "IMG_BW"
Const GOODIE_CONTENTTYPE_ANIM_COLOR = "ANIM_COLOR"
Const GOODIE_CONTENTTYPE_ANIM_BW = "ANIM_BW"
Const GOODIE_CONTENTTYPE_JUKEBOX = "JUKEBOX"

Const GOODIE_CONTENTTYPE_SOUND_MONO = "SOUND_MONO"
Const GOODIE_CONTENTTYPE_SOUND_MONO_MINI = "SOUND_MONO_MINI"
Const GOODIE_CONTENTTYPE_SOUND_POLY = "SOUND_POLY"
Const GOODIE_CONTENTTYPE_SOUND_POLY_MINI = "SOUND_POLY_MINI"
Const GOODIE_CONTENTTYPE_SOUND_HIFI = "SOUND_HIFI"
Const GOODIE_CONTENTTYPE_SOUND_FX = "SOUND_FX"

Const GOODIE_CONTENTTYPE_GAME_JAVA = "GAME_JAVA"
Const GOODIE_CONTENTTYPE_FRAME_MED = "FRAME_MEDIUM"

Const GOODIE_CONTENTTYPE_VIDEO_DWL = "VIDEO_DWL"
Const GOODIE_CONTENTTYPE_VIDEO_SOUND = "VIDEO_SOUND"
Const GOODIE_CONTENTTYPE_VIDEO_CLIP = "VIDEO_CLIP"
Const GOODIE_CONTENTTYPE_VIDEO_SSAVER = "VIDEO_SCREENSAVERSOUND"
Const GOODIE_CONTENTTYPE_VIDEO_SSAVER_NOSOUND = "VIDEO_SCREENSAVERSOUNDLESS"

Const GOODIE_URL_CATALOGSERVICE = "http://content.k-mobile.com/v2/ws/catalogservice.asmx/"
Const GOODIE_URL_DOWNLOADSERVICE = "http://content.k-mobile.com/v2/ws/Downloadservice.asmx/"
Const GOODIE_URL_SENDSERVICE = "http://content.k-mobile.com/v2/ws/Sendservice.asmx/"
Const GOODIE_URL_DRAWLOGOSERVICE = "http://content.k-mobile.com/v2/ws/DrawlogoService.asmx/"
'Const GOODIE_URL_DRAWLOGOSERVICE = "http://rome:8081/v2/ws/drawlogoservice.asmx/"
%>